import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Cloud, Loader2, RotateCcw, Trash2 } from "lucide-react";
import { listSyncIssues, resolveSyncIssue, type SyncIssue } from "./localSync";
import { useConfirmDialog } from "../../components/ConfirmDialogProvider";

function JsonValue({ value }: { value: unknown }) {
  return <pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap rounded-xl bg-elevated p-3 text-[0.7rem] leading-5 text-muted">{JSON.stringify(value, null, 2)}</pre>;
}

export function SyncIssuesPanel() {
  const confirm = useConfirmDialog();
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["sync-issues"], queryFn: listSyncIssues, refetchInterval: 5_000 });
  const mutation = useMutation({ mutationFn: ({ issue, resolution }: { issue: SyncIssue; resolution: Parameters<typeof resolveSyncIssue>[1] }) => resolveSyncIssue(issue.operationId, resolution), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["sync-issues"] }), queryClient.invalidateQueries({ queryKey: ["alerts"] })]); queryClient.invalidateQueries(); } });
  if (!query.data?.length) return <section className="surface-card p-5 sm:p-6"><p className="eyebrow">Synchronization</p><h2 className="mt-1 font-display text-xl font-black">All changes are clear</h2><p className="mt-3 flex items-center gap-2 text-sm text-success"><Cloud className="size-4" /> No saved edit needs your attention.</p></section>;
  return <section className="surface-card p-5 sm:p-6"><p className="eyebrow">Synchronization</p><h2 className="mt-1 flex items-center gap-2 font-display text-xl font-black"><AlertTriangle className="size-5 text-warning" /> Saved edits need attention</h2><div className="mt-4 space-y-4">{query.data.map((issue) => <article key={issue.operationId} className="rounded-2xl border border-warning/40 p-4"><p className="text-sm font-black capitalize">{issue.entityType.replaceAll("-", " ")}</p><p className="mt-1 text-xs text-muted">{issue.lastErrorCode?.replaceAll("_", " ")} · attempt {issue.attemptCount}</p>{issue.lastErrorCode === "conflict" && <div className="mt-3 grid gap-3 sm:grid-cols-2"><div><p className="text-xs font-bold">Your saved version</p><JsonValue value={issue.localValue} /></div><div><p className="text-xs font-bold">Cloud version</p><JsonValue value={issue.serverValue} /></div></div>}<div className="mt-4 flex flex-wrap gap-2">{issue.lastErrorCode === "conflict" ? <><button disabled={mutation.isPending || !navigator.onLine} className="secondary-button" onClick={() => mutation.mutate({ issue, resolution: "keep_local" })}><RotateCcw className="size-4" /> Keep mine and retry</button><button disabled={mutation.isPending} className="secondary-button" onClick={() => mutation.mutate({ issue, resolution: "use_server" })}><Cloud className="size-4" /> Use cloud version</button></> : <><button disabled={mutation.isPending || !navigator.onLine} className="secondary-button" onClick={() => mutation.mutate({ issue, resolution: "retry" })}>{mutation.isPending ? <Loader2 className="size-4 animate-spin" /> : <RotateCcw className="size-4" />} Retry</button><button disabled={mutation.isPending} className="secondary-button text-danger" onClick={async () => { if (await confirm({ title: "Discard saved change?", message: "Discard this saved change and any changes that depend on it?", confirmLabel: "Discard", tone: "danger" })) mutation.mutate({ issue, resolution: "discard" }); }}><Trash2 className="size-4" /> Discard</button></>}</div></article>)}</div>{mutation.error && <p role="alert" className="mt-3 text-sm font-bold text-danger">{mutation.error instanceof Error ? mutation.error.message : "The sync issue could not be changed."}</p>}</section>;
}
