import { CheckCircle2, DownloadCloud, HardDrive, Loader2, RefreshCw, Trash2, WifiOff } from "lucide-react";
import { useEffect, useState } from "react";
import { getOfflineManifest, prepareTripOffline, removeTripOffline } from "./offlinePack";
import type { OfflineManifest } from "../../lib/local-db/database";
import { useConfirmDialog } from "../../components/ConfirmDialogProvider";

export function OfflinePackControl({ tripId }: { tripId: string }) {
  const confirm = useConfirmDialog();
  const [manifest, setManifest] = useState<OfflineManifest>(); const [progress, setProgress] = useState<[number, number]>([0, 0]); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  useEffect(() => { getOfflineManifest(tripId).then(setManifest); }, [tripId]);
  const prepare = async (essentialsOnly = false) => { setWorking(true); setError(""); try { setManifest(await prepareTripOffline(tripId, (complete, total) => setProgress([complete, total]), essentialsOnly)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Offline preparation failed."); } finally { setWorking(false); } };
  const remove = async () => { if (!await confirm({ title: "Remove offline files?", message: "Remove this trip's prepared files from this browser? Cloud originals will not be deleted.", confirmLabel: "Remove files", tone: "danger" })) return; setWorking(true); try { await removeTripOffline(tripId); setManifest(undefined); } finally { setWorking(false); } };
  const ready = manifest?.state === "ready" || manifest?.state === "essentials_ready";
  return <section className={`surface-card p-5 ${ready ? "border-success/30" : ""}`}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Offline pack</p><h2 className="mt-1 font-display text-xl font-black">{manifest?.state === "essentials_ready" ? "Essentials ready" : ready ? "Ready offline" : manifest?.state === "insufficient_space" ? "More space needed" : manifest?.state === "stale" ? "Refresh needed" : "Prepare this trip"}</h2></div>{ready ? <CheckCircle2 className="size-6 text-success" /> : <HardDrive className="size-6 text-brand" />}</div><p className="mt-3 text-sm leading-6 text-muted">{ready ? `${manifest.verifiedVersionIds.length} files verified on this device.` : "Downloads every authorized current document and caches the complete structured trip."}</p>{working && <div className="mt-4"><div className="flex items-center justify-between text-xs font-bold text-muted"><span>Preparing</span><span>{progress[0]} / {progress[1]}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-line"><div className="h-full bg-success transition-[width]" style={{ width: `${progress[1] ? progress[0] / progress[1] * 100 : 15}%` }} /></div></div>}{error && <p role="alert" className="mt-3 flex gap-2 text-sm font-bold text-danger"><WifiOff className="size-4 shrink-0" />{error}</p>}<div className="flex flex-wrap gap-2"><button disabled={working} onClick={() => prepare(false)} className="secondary-button mt-4">{working ? <Loader2 className="size-4 animate-spin" /> : ready ? <RefreshCw className="size-4" /> : <DownloadCloud className="size-4" />}{ready ? "Verify full pack" : "Make available offline"}</button>{ready && <button disabled={working} onClick={remove} className="secondary-button mt-4 text-danger"><Trash2 className="size-4" /> Remove local pack</button>}{manifest?.state === "insufficient_space" && <button disabled={working} onClick={() => prepare(true)} className="secondary-button mt-4">Prepare essentials only</button>}</div>{manifest?.checkedAt && <p className="mt-3 text-xs text-muted">Checked {new Date(manifest.checkedAt).toLocaleString()}</p>}</section>;
}
